language: cpp

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - g++-5
      - clang-3.8

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8"; fi
  - $CXX --version

install:
  - wget http://bitbucket.org/eigen/eigen/get/3.2.8.tar.gz
  - tar xzf 3.2.8.tar.gz
  - mv eigen-eigen-07105f7124f9/Eigen include/

script:
  - cd test
  - make all
  - make test
