# Compilers

c_compiler:
  - clang                         # [osx]
  - gcc                           # [linux]
cxx_compiler:
  - clangxx                       # [osx]
  - gxx                           # [linux]
fortran_compiler:
  - gfortran
target_platform:
  - osx-64                        # [osx]
  - linux-64                      # [linux]
CONDA_BUILD_SYSROOT:
  - /opt/MacOSX10.9.sdk      # [osx]

# Packages
blas_impl:
  - mkl
cmake:
  - 3.14.0
mkl:
  - 2019
pybind:
  - 2.3.0
python:
  - 3.7
  - 3.6
numpy:
  - 1.16.4
eigen:
  - 3.3.7

pin_run_as_build:
  mkl:
    max_pin: x.x
  intel_openmp:
    max_pin: x.x
